version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: car_rental_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file: .env

  liquibase:
    image: liquibase/liquibase:4.23.0-alpine
    platform: linux/arm64
    profiles: ["db-migrate"]
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./liquibase:/liquibase/changelog
    command: [
      "update",
      "--changelog-file=changelog.xml",
      "--url=jdbc:postgresql://postgres:5432/${POSTGRES_DB}",
      "--username=${POSTGRES_USER}",
      "--password=${POSTGRES_PASSWORD}",
      "--logLevel=DEBUG"
    ]
    env_file: .env

volumes:
  postgres_data:
    name: car_rental_postgres_data

networks:
  default:
    name: car_rental_network
